// cppcheck-suppress-file [unusedVariable,unreadVariable]

#include <iostream>

// NOTE: We can throw an exception in a constructor to signal an error,
// and then catch that error using a standard try-catch block
// where the object is being instantiated.

// **1. Members initializer list constructor**
namespace initializer_list {
class Constructor {
 private:
  int x_, y_, z_;

 public:
  Constructor(int x, int y) : x_(x), y_(y) {
    std::cout << "Called Constructor(int x, int y) : x_(x), y_(y) \n";
    // z_{0}; // error, it already initialized, so only can do assigment
    // z_(0); // error, it already initialized, so only can do assigment
    z_ = 0;
  }

  // using brace init
  Constructor(int x, int y, int z) : x_{x}, y_{y}, z_{z} {
    std::cout << "Called Constructor(int x, int y, int z) : x_{x}, y_{y}, "
                 "z_{z} \n";
  }

  // default arguments : must always be the RIGHTMOST parameters
  explicit Constructor(int x = 1) {
    std::cout << "Called Constructor(int x = 1) \n";
    x_ = x;
    y_ = 0;
    z_ = 0;
  }

  // Constructor() = default; error:
  // ‘InitializerList::Constructor::Constructor(int)’ cannot be overloaded
  // with ‘InitializerList::Constructor::Constructor(int x = 1)’

  void print() const {
    std::cout << "x_ = " << x_ << ", y_ = " << y_ << ", z_ = " << z_ << "\n";
  }
};

void constructers() {
  std::cout << "\n--- InitializerList Constructer Examples ---\n";
  Constructor obj;
  Constructor obj1 = Constructor(1, 2);
  obj1.print();

  Constructor obj2 = Constructor(3, 4, 5);
  obj2.print();
}
}  // namespace initializer_list

// **2. Default constructor**
// - It is a constructor that accepts no arguments.
// - Generated if no constructors are declared
// - Initializes members: basic types uninitialized, class types call their default constructor
namespace default_constructor {
class UConstructors {
 public:
  // User-defined default constructor without argument
  UConstructors() { std::cout << "Called UConstructors() \n"; }
};

class IConstructors {
 public:
  // Implicit default constructor is generated by the compiler when the class
  // has no user-declared constructors
};

class EConstructors {
 public:
  // we already create the constructor ourselves
  //  EConstructors(int a)
  explicit EConstructors(float /*a*/)  // explicit ->
                                       // EConstructors obj2 = 1; [ERROR]

  {
    std::cout << "Called explicit EConstructors(int a) \n";
  }

  // Explicit default constructor : also want the compiler to generate the
  // default constructor.
  EConstructors() = default;
};

void constructers() {
  std::cout << "\n--- Default Constructer Examples ---\n";
  UConstructors obj1;
  //   UConstructors obj2(); // wrong, this is function declare
  // FYI:
  // void outer()
  // {
  //     void helper();
  //     helper(); // defined later in the same file
  // }

  UConstructors obj3{};

  IConstructors obj4;
  IConstructors obj6{};

  EConstructors obj7;
  EConstructors obj9{};

  EConstructors obj10(1.2);
  EConstructors obj11{2};
}
}  // namespace default_constructor

// **3. Delegate constructor: allow to delegate initialization to another**
// constructor Never generated automatically
namespace delegate {
class Constructor {
 private:
  int x_;
  int y_;

 public:
  Constructor(int x, int y) : x_{x}, y_{y} {
    std::cout << "Called  Constructor(int x, int y) : x_{x}, y_{y} \n";
  }

  explicit Constructor(int x) : Constructor{x, 1} {
    std::cout << "Called   Constructor(int x):Constructor(x,0) \n";
  }

  Constructor() : Constructor(0) {
    std::cout << "Called    Constructor() : Constructor(0) \n";
  }

  void print() const { std::cout << "x_ = " << x_ << ", y_ = " << y_ << "\n"; }
};

void constructors() {
  std::cout << "\n--- Delegate Constructer Examples ---\n";
  Constructor obj1 = Constructor();
  obj1.print();
}
}  // namespace delegate

// **4.  Copy constructor:  initialize an copy object with an existing object**
// - Generated if no copy/move constructor or `destructor` is declared
// - Performs memberwise (shallow) copy
//  * Copy constructor
//      Object obj1 = obj2
//      Object obj1(obj2)
//      Object obj1{obj2}
//  * Copy assigment
//      obj1 = obj1
namespace copy {
class IConstructor  // C++ will create a public implicit copy constructor for us
                    // if we do not provide a one.
{
 private:
  int x_;
  int y_;

 public:
  IConstructor(int x, int y) : x_{x}, y_{y} {
    std::cout << "Called  IConstructor(int x, int y) : x_{x}, y_{y} \n";
  }

  void print() const { std::cout << "x_ = " << x_ << ", y_ = " << y_ << "\n"; }
};

class EConstructor  // explicitly define our own copy constructor
{
 private:
  int x_;
  int y_;

 public:
  EConstructor(int x, int y) : x_{x}, y_{y} {
    std::cout << "Called  IConstructor(int x, int y) : x_{x}, y_{y} \n";
  }

  // Implicit Copy constructor if there is no desconstrutor
  // using `default` keyword
  // EConstructor(const EConstructor &ref) = default;

  // Explicit Copy constructor (a=EConstructor(b))
  EConstructor(const EConstructor& ref) : x_{ref.x_}, y_{ref.x_} {
    std::cout << "Called  EConstructor(const EConstructor& ref) : x_{ref.x_}, "
                 "y_{ref.x_} \n";
  }

  // Copy assigment (a=b)
  EConstructor& operator=(const EConstructor& other) {
    if (this != &other) {
      this->x_ = other.x_;
      this->y_ = other.y_;
    }
    return *this;
  }

  void print() const { std::cout << "x_ = " << x_ << ", y_ = " << y_ << "\n"; }
};

class DeConstructor  // Delete the copy constructor so no copies can be made
{
 private:
  int x_;
  int y_;

 public:
  DeConstructor(int x, int y) : x_{x}, y_{y} {
    std::cout << "Called  DeConstructor(int x, int y) : x_{x}, y_{y} \n";
  }

  // using `delete` keyword
  DeConstructor(const DeConstructor& fraction) = delete;

  void print() const { std::cout << "x_ = " << x_ << ", y_ = " << y_ << "\n"; }
};

void constructors() {
  std::cout << "\n--- Copy Constructer Examples ---\n";
  IConstructor obj1 = IConstructor(1, 2);
  IConstructor obj2{obj1};
  obj1.print();
  obj2.print();

  EConstructor obj3 = EConstructor(3, 4);
  EConstructor obj4{obj3};
  obj3.print();
  obj4.print();

  DeConstructor obj5 = DeConstructor(5, 6);
  // DeConstructor obj6{obj5}; error
  obj5.print();
}
}  // namespace copy

// **4. Move Constructor**
// - Move constructor and move assignment transfer resource ownership
// - from one object to another. This is usually cheaper than copying.
// - A move constructor is implicitly generated only if no user-declared
//   copy constructor, move constructor, or destructor exists.
namespace move {
class Model  // C++ will create a public implicit copy constructor for us if we
             // do not provide a one.
{
 private:
  int x_;
  int y_;

 public:
  Model(int x, int y) : x_{x}, y_{y} { std::cout << "Call constructor \n"; }

  ~Model() { std::cout << "Call destructor \n"; }

  Model(const Model& other) : Model(other.x_, other.y_) {
    std::cout << "Call copy constructor \n";
  }

  Model& operator=(const Model& other) {
    std::cout << "Call copy assigment \n";
    if (this != &other) {
      this->x_ = other.x_;
      this->y_ = other.y_;
    }
    return *this;
  }

  Model(Model&& source) noexcept : x_(source.x_), y_(source.y_) {
    std::cout << "Call move constructor\n";

    // reset source
    source.x_ = 0;
    source.y_ = 0;
  }

  Model& operator=(Model&& source) noexcept {
    std::cout << "Call move assigment \n";
    if (this != &source) {
      this->x_ = source.x_;
      this->y_ = source.y_;

      // reset source
      source.x_ = 0;
      source.y_ = 0;
    }

    return *this;
  }

  void print() const { std::cout << "x_ = " << x_ << ", y_ = " << y_ << "\n"; }
};

void constructers() {
  std::cout << "\n--- Move Constructor Examples ---\n";
  Model a(10, 20);

  std::cout << "\nCase 1: Model b = std::move(a);\n";
  Model b = std::move(a);  // move constructor

  std::cout << "\nCase 2: Model c(5,6); c = std::move(b);\n";
  Model c(5, 6);
  c = std::move(b);  // move assignment
  std::cout << "\n";
}
}  // namespace move

#include "ExampleRegistry.h"

class Constructor : public IExample {
 public:
  std::string group() const override { return "core/class"; }
  std::string name() const override { return "Constructor"; }
  std::string description() const override { return ""; }
  void execute() override {
    initializer_list::constructers();
    default_constructor::constructers();
    delegate::constructors();
    copy::constructors();
    move::constructers();
  }
};

REGISTER_EXAMPLE(Constructor, "core/class", "Constructor");
