#!/usr/bin/env bash
# Publish a Home page to the GitHub wiki that points at the generated
# documentation.
#
#   ./scripts/publish_wiki.sh                                  # wiki of the 'origin' remote
#   ./scripts/publish_wiki.sh https://github.com/me/repo.wiki.git
#   DRY_RUN=1 ./scripts/publish_wiki.sh                        # only print the page
#
# The GitHub wiki stores Markdown, so it cannot host the Doxygen HTML itself.
# This script writes a Home page that links to the GitHub Pages site (published
# by .github/workflows/docs.yml) and to the documentation in the repository.
# See docs/doxygen.md.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
WIKI_URL="${1:-}"

# Derive the wiki URL and the Pages URL from the origin remote when not given.
origin="$(git -C "$REPO_ROOT" remote get-url origin 2>/dev/null || true)"
if [[ -z "$origin" ]]; then
    echo "[ERR] no 'origin' remote; pass the wiki URL as an argument" >&2
    exit 1
fi

# https://github.com/<owner>/<repo>[.git] or git@github.com:<owner>/<repo>.git
slug="${origin##*github.com}"
slug="${slug#[:/]}"
slug="${slug%.git}"
owner="${slug%%/*}"
repo="${slug##*/}"

if [[ -z "$owner" || -z "$repo" || "$owner" == "$slug" ]]; then
    echo "[ERR] origin is not a GitHub remote ($origin); pass the wiki URL as an argument" >&2
    exit 1
fi

WIKI_URL="${WIKI_URL:-https://github.com/$owner/$repo.wiki.git}"
PAGES_URL="https://$owner.github.io/$repo/"
BLOB="https://github.com/$owner/$repo/blob/master"

page="$(cat <<PAGE
# $repo

*This page is generated by \`scripts/publish_wiki.sh\`. Edits made here are overwritten.*

## Documentation

- **[API documentation]($PAGES_URL)** - generated with Doxygen on every push to \`master\`
- [Learning path]($BLOB/docs/learning-path.md) - a suggested order through the examples
- [Adding examples]($BLOB/docs/adding-examples.md) - how the lab works and how to extend it
- [Topic index]($BLOB/docs/README.md) - every module and what it covers
- [Doxygen setup]($BLOB/docs/doxygen.md) - generating and publishing these pages

## Quick start

\`\`\`bash
git clone https://github.com/$owner/$repo.git
cd $repo
cmake -S . -B build
cmake --build build -j
./build/bin/cpp_lab_project          # interactive menu
./build/bin/cpp_lab_project --help   # command line
\`\`\`
PAGE
)"

if [[ -n "${DRY_RUN:-}" ]]; then
    echo "$page"
    exit 0
fi

work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT

echo "[INFO] cloning $WIKI_URL"
if ! git clone --quiet --depth 1 "$WIKI_URL" "$work/wiki"; then
    echo "[ERR] could not clone the wiki." >&2
    echo "      Create it first: open the repository's Wiki tab and save any page." >&2
    exit 1
fi

echo "$page" > "$work/wiki/Home.md"

if git -C "$work/wiki" diff --quiet; then
    echo "[OK] the wiki is already up to date"
    exit 0
fi

git -C "$work/wiki" add Home.md
git -C "$work/wiki" commit --quiet -m "Update Home from scripts/publish_wiki.sh"
git -C "$work/wiki" push --quiet
echo "[OK] published https://github.com/$owner/$repo/wiki"
